[update] : Added checking argument

diff --git a/src/crshini b/src/crshini
--- a/src/crshini
+++ b/src/crshini
@@ -107,24 +107,33 @@ if [[ "${mode}" = "none" ]]; then
     exit 1
 fi
 
-file="${1=""}"
-section="${2-""}"
-param="${3-""}"
-value="${4-""}"
-
-export _crshini_debug=true
+# _check_arg <min arg quantity> <max arg quantity> "${@}"
+_check_arg(){
+    local _arg_min="${1}" _arg_max="${2}" && shift 2
+    if (( "${#}" < _arg_min )); then
+        echo "At least ${_arg_min} arguments are required."
+        exit 1
+    elif (( "${#}" > _arg_max )) && (( _arg_max != 0 )); then
+        echo "You cannot specify more than ${_arg_max} arguments."
+        exit 1
+    fi
+}
 
 case "${mode}" in
     "get")
-        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_get "${file}" "${section}" "${param}"
+        _check_arg 1 3 "${@}"
+        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_get "${@}"
         ;;
     "set")
-        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_set "${file}" "${section}" "${param}" "${value}"
+        _check_arg 4 4 "${@}"
+        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_set "${@}"
         ;;
     "merge")
-        _crshini_output="${output}" _crshini_stdin=true _crshini_merge "${file}" "${section}"
+        _check_arg 1 2 "${@}"
+        _crshini_output="${output}" _crshini_stdin=true _crshini_merge "${@}"
         ;;
     "del")
-        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_del "${file}" "${section}" "${param}"
+        _check_arg 1 0 "${@}"
+        _crshini_output="${output}" _crshini_stdin="${stdin}" _crshini_del "${@}"
         ;;
 esac
